name: CI suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --all-targets --all-features --verbose

      - name: Build `no-std`
        run: cargo build --no-default-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Check format
        run: cargo fmt --all --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features --verbose -- -D warnings